-- MySQL Script generated by MySQL Workbench
-- Fri Sep  1 16:21:54 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema spider
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema spider
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `spider` DEFAULT CHARACTER SET utf8 ;
USE `spider` ;

-- -----------------------------------------------------
-- Table `spider`.`lago_city`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spider`.`lago_city` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `city_id` INT(11) NULL DEFAULT NULL COMMENT '城市id',
  `parent_id` INT(11) NULL DEFAULT NULL,
  `name` VARCHAR(45) NULL DEFAULT NULL COMMENT '城市名称',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '城市列表';


-- -----------------------------------------------------
-- Table `spider`.`lago_company`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spider`.`lago_company` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `company_id` INT(11) NULL DEFAULT NULL COMMENT '公司id',
  `full_name` VARCHAR(255) NULL DEFAULT NULL COMMENT '公司全称',
  `short_name` VARCHAR(255) NULL DEFAULT NULL COMMENT '公司简称',
  `size` VARCHAR(45) NULL DEFAULT NULL COMMENT '规模',
  `logo` VARCHAR(255) NULL DEFAULT NULL COMMENT '公司logo',
  `industry` VARCHAR(45) NULL DEFAULT NULL,
  `finance_stage` VARCHAR(45) NULL DEFAULT NULL COMMENT '融资情况',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `spider`.`lago_hr`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spider`.`lago_hr` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `user_id` INT(11) NULL DEFAULT NULL COMMENT 'Hr id',
  `position_name` VARCHAR(45) NULL DEFAULT NULL COMMENT 'Hr 的职位',
  `phone` INT(11) NULL DEFAULT NULL COMMENT '联系电话',
  `email` VARCHAR(45) NULL DEFAULT NULL COMMENT '邮箱',
  `portrait` VARCHAR(250) NULL DEFAULT NULL COMMENT '头像',
  `real_name` VARCHAR(45) NULL DEFAULT NULL COMMENT '名字',
  `position_id` INT(11) NULL DEFAULT NULL COMMENT '职位id',
  `actice_time` VARCHAR(45) NULL DEFAULT NULL COMMENT '活跃时间',
  `connection_lago` VARCHAR(255) NULL DEFAULT NULL COMMENT '拉钩的对话链接',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'Hr信息';


-- -----------------------------------------------------
-- Table `spider`.`lago_recruit_day`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spider`.`lago_recruit_day` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `position_id` INT(11) NULL DEFAULT NULL COMMENT '职位id',
  `position_name` VARCHAR(255) NULL DEFAULT NULL COMMENT '职位名称',
  `position_lables` VARCHAR(255) NULL DEFAULT NULL COMMENT '职位标签',
  `salary` VARCHAR(45) NULL DEFAULT NULL COMMENT '薪水',
  `work_year` VARCHAR(45) NULL DEFAULT NULL COMMENT '年限',
  `education` VARCHAR(45) NULL DEFAULT NULL COMMENT '学历',
  `job_nature` VARCHAR(45) NULL DEFAULT NULL COMMENT '工作性质',
  `first_type` VARCHAR(45) NULL DEFAULT NULL COMMENT '一级类别',
  `second_type` VARCHAR(45) NULL DEFAULT NULL COMMENT '二级类别',
  `city` VARCHAR(45) NULL DEFAULT NULL COMMENT '城市',
  `district` VARCHAR(45) NULL DEFAULT NULL COMMENT '区域',
  `company_id` INT(11) NULL DEFAULT NULL COMMENT '公司id',
  `position_advantage` VARCHAR(255) NULL DEFAULT NULL COMMENT '职位诱惑',
  `location` VARCHAR(45) NULL DEFAULT NULL COMMENT '工作地点',
  `publisher_id` INT(11) NULL DEFAULT NULL COMMENT 'hr的id ',
  `publish_time` VARCHAR(45) NULL DEFAULT NULL COMMENT '发布时间',
  `department` VARCHAR(45) NULL DEFAULT NULL COMMENT '招聘部门',
  `describe` LONGTEXT NULL DEFAULT NULL COMMENT '拉钩每日招聘信息',
  `create_time` INT(11) NULL DEFAULT NULL COMMENT '创建时间',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
