-- MySQL Script generated by MySQL Workbench
-- Mon Sep 18 11:06:33 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema spider
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema spider
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `spider` DEFAULT CHARACTER SET utf8 ;
USE `spider` ;

-- -----------------------------------------------------
-- Table `spider`.`lagou_city`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spider`.`lagou_city` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `parent_id` INT(11) NULL DEFAULT NULL,
  `city_name` VARCHAR(45) NULL DEFAULT NULL COMMENT '城市名称',
  `name_initial` VARCHAR(45) NULL DEFAULT NULL COMMENT '城市名称首字母',
  `created_at` INT(11) NULL DEFAULT NULL COMMENT '创建时间',
  `num` INT(11) NOT NULL DEFAULT '0' COMMENT '该城市职位记录数量',
  `total_num` INT(11) NULL DEFAULT NULL COMMENT '该城市发布职位总数',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`city_name` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '城市列表';


-- -----------------------------------------------------
-- Table `spider`.`lagou_company`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spider`.`lagou_company` (
  `company_id` INT(11) NOT NULL COMMENT '公司id',
  `full_name` VARCHAR(255) NULL DEFAULT NULL COMMENT '公司全称',
  `short_name` VARCHAR(255) NULL DEFAULT NULL COMMENT '公司简称',
  `size` VARCHAR(45) NULL DEFAULT NULL COMMENT '规模',
  `logo` VARCHAR(255) NULL DEFAULT NULL COMMENT '公司logo',
  `industry` VARCHAR(45) NULL DEFAULT NULL,
  `finance_stage` VARCHAR(45) NULL DEFAULT NULL COMMENT '融资情况',
  `created_at` INT(11) NULL DEFAULT NULL COMMENT '创建时间',
  `num` INT(11) NOT NULL DEFAULT '0' COMMENT '该公司记录的职位数量',
  PRIMARY KEY (`company_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `spider`.`lagou_hr`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spider`.`lagou_hr` (
  `publisher_id` INT(11) NOT NULL COMMENT 'Hr id',
  `position_name` VARCHAR(45) NULL DEFAULT NULL COMMENT 'Hr 的职位',
  `portrait` VARCHAR(250) NULL DEFAULT NULL COMMENT '头像',
  `real_name` VARCHAR(45) NULL DEFAULT NULL COMMENT '名字',
  `position_id` INT(11) NULL DEFAULT NULL COMMENT '职位id',
  `active_time` VARCHAR(45) NULL DEFAULT NULL COMMENT '活跃时间',
  `connection_lagou` VARCHAR(255) NULL DEFAULT NULL COMMENT '拉钩的对话链接',
  `created_at` INT(11) NULL DEFAULT NULL COMMENT '创建时间',
  `num` INT(11) NOT NULL DEFAULT '0' COMMENT '该hr的职位记录数量',
  PRIMARY KEY (`publisher_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'Hr信息';


-- -----------------------------------------------------
-- Table `spider`.`lagou_recruit_day`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spider`.`lagou_recruit_day` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `position_id` INT(11) NULL DEFAULT NULL COMMENT '职位id',
  `position_name` VARCHAR(255) NULL DEFAULT NULL COMMENT '职位名称',
  `position_labels` VARCHAR(255) NULL DEFAULT NULL COMMENT '职位标签',
  `salary` VARCHAR(45) NULL DEFAULT NULL COMMENT '薪水',
  `work_year` VARCHAR(45) NULL DEFAULT NULL COMMENT '年限',
  `education` VARCHAR(45) NULL DEFAULT NULL COMMENT '学历',
  `job_nature` VARCHAR(45) NULL DEFAULT NULL COMMENT '工作性质',
  `first_type` VARCHAR(45) NULL DEFAULT NULL COMMENT '一级类别',
  `second_type` VARCHAR(45) NULL DEFAULT NULL COMMENT '二级类别',
  `city` VARCHAR(45) NULL DEFAULT NULL COMMENT '城市',
  `district` VARCHAR(45) NULL DEFAULT NULL COMMENT '区域',
  `company_id` INT(11) NULL DEFAULT NULL COMMENT '公司id',
  `position_advantage` VARCHAR(255) NULL DEFAULT NULL COMMENT '职位诱惑',
  `location` VARCHAR(225) NULL DEFAULT NULL COMMENT '工作地点',
  `publisher_id` INT(11) NULL DEFAULT NULL COMMENT 'hr的id ',
  `publish_time` VARCHAR(45) NULL DEFAULT NULL COMMENT '发布时间',
  `department` VARCHAR(45) NULL DEFAULT NULL COMMENT '招聘部门',
  `content` LONGTEXT NULL DEFAULT NULL COMMENT '拉钩每日招聘信息',
  `created_at` INT(11) NULL DEFAULT NULL COMMENT '创建时间',
  `url` VARCHAR(255) NULL DEFAULT NULL COMMENT '网页链接',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `position_id_UNIQUE` (`position_id` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
